### ISSUE TITLE
Failed to instantiate module ngMaterial

### ISSUE THREAD

**Issue by TheNando** [Ashkettle/ashkettle-ngmaterial#4]
I was working on a Meteor app using urigo:angular, urigo:angular-ui-router, and ashkettle:ngmaterial. It was working fine until I updated Meteor and all the packages I was using. Since then ngMaterial will not instantiate, giving the following error message:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module test due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:nomod] Module 'ngMaterial' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.8/$injector/nomod?p0=ngMaterial
    at REGEX_STRING_REGEXP (http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:92:12)
    at http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:1793:17
    at ensure (http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:1717:38)
    at module (http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:1791:14)
    at http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:4123:22
    at forEach (http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:352:20)
    at loadModules (http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:4107:5)
    at http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:4124:40
    at forEach (http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:352:20)
    at loadModules (http://mydomain.com:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:4107:5)
```

Unfortunately, I don't recall the previous versions and trying to revert back manually has proven unsuccessful. Here are the current versions of the packages I'm using:

meteor-platform: 1.2.1
urigo:angular: 0.6.0
urigo:angular-ui-router: 0.6.2 
ashkettle:ngmaterial: 1.1.0

I have created a very simple app to reduce the problem's scope for easier troubleshooting. I only have two files in my project:

test.html
```
<head>
  <title>test</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  <div ng-app="test" ng-controller="testctrl">
    <button ng-click="test()">ToastTest</button>
  </div>
</body>
```

and test.js
```
if (Meteor.isClient) {
  var test = angular.module('test', ['angular-meteor', 'ui.router', 'ngMaterial']);

  test.controller('testctrl', ['$scope', '$mdToast', function ($scope, $mdToast) {
    $scope.test = function() {
      $mdToast.show($mdToast.simple().content('This is a test'));
    };
  }]);
}
```

This is sufficient to reproduce the error for me.

**Comment by IGx89** [comment]
Also seeing this issue myself after upgrading. Looks like the contents of angular-material.html from the package aren't being injected into the app's HTML page for some reason

**Comment by Ashkettle** [comment]
Yeah, I've confirmed this.  I'm working on it now and should have something tonight or tomorrow.

**Comment by dasilvacontin** [comment]
+1. Can't work with latest version

**Comment by Ashkettle** [comment]
Sorry this took so long to fix.  I couldn't figure out what was going wrong.  I switched tactics to get it out and working to all of you.  As of now, it's working and confirmed on Nando's test also.

**Comment by dasilvacontin** [comment]
Thanks!

**Comment by gokultrycinema** [comment]
Uncaught Error: [$injector:modulerr] Failed to instantiate module portal due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:nomod] Module 'ngMaterial' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=ngMaterial
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:2082:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:2006:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:2080:14)
    at http://localhost:9000/bower_components/angular/angular.js:4617:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:321:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4601:5)
    at http://localhost:9000/bower_components/angular/angular.js:4618:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:321:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4601:5)
